#!/usr/bin/env bash
#
# bridge-add-root.sh — Phase F V0.6.a.
#
# Adds a NARROW bind mount for one content root to the bridge and recreates the
# container. This is the human-in-the-loop way to widen the bridge's filesystem
# view: the container has NO Docker socket and can never add its own mounts —
# only this script (run by you on the host) can. The SaaS "needs_mount" banner
# generates the exact command to paste here.
#
# Each root mounts at its MIRRORED container path so resolution is deterministic
# and debuggable:
#     host  /volume1/photo/Content  ->  container  /sources/host/volume1/photo/Content
#
# The script owns a state file (.bridge-roots) and REGENERATES the whole compose
# override (docker-compose.binds.yml) from it each run — it never relies on
# Docker Compose's volume-merge semantics.
#
# Usage:
#     ./scripts/bridge-add-root.sh "/volume1/photo/Content"            # read-only
#     ./scripts/bridge-add-root.sh "/volume1/photo/Content" --writable # RW (create-project)
#     ./scripts/bridge-add-root.sh "/volume1/photo/Content" --dev      # target the dev stack
#
# After it runs, add the root in the SaaS UI (or via the gateway POST
# /internal/devices/:id/source-roots) so the bridge resolves + reports it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SCRIPT_DIR"

HOST_PATH=""
MODE="ro"
DEV=0

for arg in "$@"; do
  case "$arg" in
    --writable) MODE="rw" ;;
    --dev) DEV=1 ;;
    --*) echo "unknown flag: $arg" >&2; exit 2 ;;
    *)
      if [ -n "$HOST_PATH" ]; then
        echo "only one host path may be added per invocation" >&2; exit 2
      fi
      HOST_PATH="$arg"
      ;;
  esac
done

if [ -z "$HOST_PATH" ]; then
  echo "usage: ./scripts/bridge-add-root.sh \"/abs/host/path\" [--writable] [--dev]" >&2
  exit 2
fi
case "$HOST_PATH" in
  /*) : ;;
  *) echo "host path must be absolute: $HOST_PATH" >&2; exit 2 ;;
esac
case "$HOST_PATH" in
  *..*) echo "host path must not contain '..': $HOST_PATH" >&2; exit 2 ;;
esac
if [ ! -d "$HOST_PATH" ]; then
  echo "host path does not exist (or is not a directory) on this machine: $HOST_PATH" >&2
  exit 1
fi

if [ "$DEV" -eq 1 ]; then
  STATE_FILE=".bridge-roots.dev"
  BINDS_FILE="docker-compose.binds.dev.yml"
  BASE_FILE="docker-compose.dev.yml"
  SERVICE="four-nations-bridge-dev"
else
  STATE_FILE=".bridge-roots"
  BINDS_FILE="docker-compose.binds.yml"
  BASE_FILE="docker-compose.yml"
  SERVICE="four-nations-bridge"
fi

# Record the root in the state file (deduped on host path; last mode wins).
touch "$STATE_FILE"
TMP_STATE="$(mktemp)"
# Keep every line whose host path (field 1, tab-delimited) differs from this one.
awk -F '\t' -v hp="$HOST_PATH" '$1 != hp' "$STATE_FILE" > "$TMP_STATE" || true
printf '%s\t%s\n' "$HOST_PATH" "$MODE" >> "$TMP_STATE"
mv "$TMP_STATE" "$STATE_FILE"

# Regenerate the whole override from the state file (full-list regen).
{
  echo "# GENERATED by bridge-add-root.sh — do NOT edit by hand."
  echo "# Narrow per-root bind mounts; container path mirrors the host path."
  echo "services:"
  echo "  ${SERVICE}:"
  echo "    volumes:"
  while IFS="$(printf '\t')" read -r hp mode; do
    [ -z "$hp" ] && continue
    echo "      - \"${hp}:/sources/host${hp}:${mode}\""
  done < "$STATE_FILE"
} > "$BINDS_FILE"

echo "Wrote $BINDS_FILE:"
sed 's/^/    /' "$BINDS_FILE"
echo ""
echo "Recreating the bridge container with the narrow bind(s)…"
docker compose -f "$BASE_FILE" -f "$BINDS_FILE" up -d --build

echo ""
echo "Done. '$HOST_PATH' is now mounted ${MODE} at /sources/host${HOST_PATH}."
if [ "$MODE" = "rw" ]; then
  echo "It is WRITABLE — eligible for create-project (add-only; the NAS user"
  echo "should have write-but-no-delete on it; see arch-note 14 §3)."
fi
echo "Next: add this root in the SaaS UI so the bridge resolves + reports it."
echo ""
echo "IMPORTANT — to start/restart the bridge later, use ./scripts/bridge-up.sh${DEV:+ --dev}"
echo "(or 'docker compose stop'/'start'). A bare 'docker compose up -d' WITHOUT the"
echo "binds file recreates the container and DROPS this mount."
